### ISSUE TITLE
Template fails on Windows

### ISSUE THREAD

**Issue by xmlking** [marklogic/slush-marklogic-node#75] opened 2015-03-20 21:45 UTC
after installing `slush` and `slush-marklogic-node`
```
npm install -g slush
npm install -g slush-marklogic-node
```
`slush marklogic-node mldemo` only produce in `ml.bat` not the project scaffolding.

which version of node it is compatible with? I am using iojs v1.2.0

**Comment by grtjn** [comment] 2015-03-23 11:58
I'm running regular nodejs (v0.10.26) myself, I don't think any of us tried with iojs. Did it return any error messages?

By the way, note that you need to install gulp globally as well..

**Comment by xmlking** [comment] 2015-03-23 22:16
I switched to  nodejs (v0.10.26)  and run the same  above commands. At the end I only see `ml.bat` no errors.  
I am using windows 7. Not sure why I am not getting project generated!

Yes I have gulp installed as globe.
```
C:\Work\slushmarklogic>gulp -v
[15:13:56] CLI version 0.1.5
```

```bash
C:\Work\slushmarklogic>slush marklogic-node sumoml
[slush] Using slushfile C:\SMS\nvmw\v0.10.26\node_modules\slush-marklogic-node\s
lushfile.js
[15:11:04] Starting 'marklogic-node:init'...
[?] Name for the app? sumoml
[?] Roxy App Type? rest
[?] Roxy Branch? dev
[?] Include ESRI Maps? No
Retrieving Roxy script
Got Roxy script
chmod done; appName=sumoml; appType=rest; branch=dev
Spawning Roxy new command: ml.bat new sumoml --app-type=rest --server-version=7
--branch=dev
done running ml new

C:\Work\slushmarklogic>dir
 Volume in drive C is OS
 Volume Serial Number is 32C7-CF93

 Directory of C:\Work\slushmarklogic

03/23/2015  03:11 PM    <DIR>          .
03/23/2015  03:11 PM    <DIR>          ..
03/23/2015  03:11 PM             4,394 ml.bat
               1 File(s)          4,394 bytes
               2 Dir(s)  416,953,044,992 bytes free

C:\Work\slushmarklogic>
```

**Comment by xmlking** [comment] 2015-03-23 22:28
Looks like it is not running `ml.bat` command as part of `slush marklogic-node sumoml` command.
I manically run following command.  and it produced following structure. I don't see `gulpfile.js`
wonder if it has been tested on `Wondows` and `MarkLogic 8`

```bash
ml.bat new sumoml --app-type=rest --server-version=7
```
![image](https://cloud.githubusercontent.com/assets/627951/6791994/e1475cca-d170-11e4-9be4-a5894323fa0f.png)

**Comment by grtjn** [comment] 2015-03-24 09:48
The slush templates first runs ml.bat, but should copy extra files into the created folder, and do some finishing touches in the end. Looks like it wasn't tested properly on Windows.

Note also that Roxy (ml.bat and other files above) depends on Ruby. Is that installed on your system?

**Comment by grtjn** [comment] 2015-03-24 10:50
I'm able to reproduce the issue on Windows 8(.1) with nodejs 0.12.1. No warning whatsoever. I'll see if I can dig in deeper. Looks like spawn of ml.bat is misbehaving, and causing a premature termination of the slush processing..

**Comment by grtjn** [comment] 2015-03-24 11:21
The stderr is not propagated to console. Fixing that reveals that we shouldn't call ml.bat with ./ml.bat.

I am also noticing something with gulp-install which reports it cannot run bower install headless. You should be able to run bower install from command-line though..

**Comment by grtjn** [comment] 2015-03-24 11:27
PR pending..

**Comment by grtjn** [comment] 2015-04-15 13:54
PR was merged

**Closed** 2015-04-15 13:54 UTC
Labels: bug
