### ISSUE TITLE
Clicking create requires (second) login

### ISSUE THREAD

**Issue by grtjn** [marklogic/slush-marklogic-node#141] opened 2015-09-03 14:16 UTC
After logging in for search, you need to login again if you open create.

**Comment by hunterwilliams** [comment] 2015-09-04 17:57
I manage to get create to open but if you open it in a new tab or do a reload it fails to throws up the user login. This does not happen for search however.

**Comment by grtjn** [comment] 2015-09-04 19:00
Could create be handled differently than search? The logic should be the same I think..

**Comment by hunterwilliams** [comment] 2015-09-04 19:08
That's where I started poking around. Nothing that seemed different seemed to actually cause it. My assumption is the login interceptor is popping too quick but I can't confirm that

**Comment by hunterwilliams** [comment] 2015-09-05 04:06
Difference is in routes.js

``
      loginService.protectedRoutes(['root.create', 'root.profile']);
``

So root.search isn't there and it works properly. My guess is something needs to be fixed with protected routes or something.

**Comment by grtjn** [comment] 2015-09-05 05:03
Good find. Actually, looks like _adding_ root.search to the protectedRoutes makes things work better..

**Comment by grtjn** [comment] 2015-09-05 05:23
The other question that raises to my head, a search was showing a login before, but why was the fact one logged it not properly recorded? Maybe the isAuthenticated in the login service needs a little more attention?

**Comment by hunterwilliams** [comment] 2015-09-06 08:47
So I dug into this -

@grtjn - correct that we need to add root.search to protectedRoutes but.......

The problem is that https://github.com/marklogic/slush-marklogic-node/blob/master/app/templates/ui/app/login/login.service.js#L12 is never remedied. The whole login service has no idea whether the user is logged in or not. It can't even ask properly.

Since you shouldn't/can't add a dependency of userservice to loginservice and otherwise you likely keep the problem without weirdness - I started moving over checking status from userservice to loginservice. (see: https://github.com/hunterwilliams/slush-marklogic-node/tree/login-status-fix). However, it fails to resolve the promise in time and honestly it starts to probably break the interceptor and such, but I think it's down the road of what we need. 

@ryanjdew if I'm not breaking the interceptor let me know and I can continue. If the promise issue can't be resolved easily - could we possibly allow the login success call to pop the user from the login page or would that be just opening us up to other issues?

**Comment by grtjn** [comment] 2015-09-06 10:51
Can't you provide userservice as a listener to loginservice? Keeps it generic, but does allow handing over  checking status to external service. Not sure that is going to be easier, just thinking out-loud here..

**Comment by hunterwilliams** [comment] 2015-09-07 13:37
@grtjn Not really without making weird dependencies :arrows_clockwise:

**Comment by grtjn** [comment] 2015-09-07 13:57
(nice icon)

Yes, but as long as one side uses listener pattern, then one of both doesn't need to know details about the other. Listener pattern is for such cases I'd say..

**Comment by grtjn** [comment] 2015-09-07 13:58
But perhaps you could do a PR to show what you have so far. Maybe that makes things clearer..

**Comment by hunterwilliams** [comment] 2015-09-07 14:05
I'll PR it now then. I don't disagree, just may require some design decisions that alter it's current state.

**Closed** 2015-09-16 18:48 UTC
Labels: bug
